# Generated by Django 4.1.2 on 2022-10-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0002_alter_systemuser_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='hospital_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='sur_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
