# Generated by Django 4.1.2 on 2022-10-17 05:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livedata', '0004_remove_systemuser_sur_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueX', models.FloatField(default=0)),
                ('valueY', models.FloatField(default=0)),
                ('valueZ', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=128)),
                ('description', models.TextField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam'), (2, 'Không rõ')], default=0)),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gyroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueX', models.FloatField(default=0)),
                ('valueY', models.FloatField(default=0)),
                ('valueZ', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HasPatientFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.familiar')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.device')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam'), (2, 'Không rõ')], default=0)),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 17, 12, 47, 44, 51474))),
                ('acceleration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.acceleration')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.device')),
                ('gyroscope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.gyroscope')),
            ],
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotationX', models.FloatField(default=0)),
                ('rotationY', models.FloatField(default=0)),
                ('rotationZ', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShareAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livedata.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livedata.province')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livedata.ward')),
            ],
        ),
        migrations.CreateModel(
            name='TouchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SystemUser',
        ),
        migrations.AddField(
            model_name='rotation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.unit'),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='rotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.rotation'),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='touch_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.touchstatus'),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='share_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.shareaddress'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.patientinfo'),
        ),
        migrations.AddField(
            model_name='haspatientfamiliar',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.patient'),
        ),
        migrations.AddField(
            model_name='gyroscope',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.unit'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='share_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.shareaddress'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='share_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.shareaddress'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceleration',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livedata.unit'),
        ),
    ]
