# Generated by Django 4.1.2 on 2022-10-24 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueX', models.FloatField(default=0)),
                ('valueY', models.FloatField(default=0)),
                ('valueZ', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gyroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueX', models.FloatField(default=0)),
                ('valueY', models.FloatField(default=0)),
                ('valueZ', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TouchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotationX', models.FloatField(default=0)),
                ('rotationY', models.FloatField(default=0)),
                ('rotationZ', models.FloatField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 24, 15, 45, 21, 166723))),
                ('acceleration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.acceleration')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.device')),
                ('gyroscope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.gyroscope')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.rotation')),
                ('touch_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.touchstatus')),
            ],
        ),
        migrations.AddField(
            model_name='gyroscope',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.unit'),
        ),
        migrations.AddField(
            model_name='acceleration',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.unit'),
        ),
    ]
