# Generated by Django 4.1.2 on 2022-10-25 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 12, 30, 59, 699559)),
        ),
    ]
