# Generated by Django 4.1.2 on 2022-10-25 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_rawdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 12, 37, 12, 930564)),
        ),
    ]
