# Generated by Django 4.1.2 on 2022-10-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_systemuser_district_province_ward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='district',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='province',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='ward',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
