# Generated by Django 4.1.2 on 2022-10-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='district',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='province',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='ward',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
