# Generated by Django 4.1.2 on 2022-10-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
